// src/constants/products.ts
import {images} from '../assets/images/images';
import {ProductItem} from '../types';

export const aataProducts: ProductItem[] = [
  {
    id: 'aata_1',
    name: 'Khapali Gehun',
    price: '80₹',
    image: images.aata,
    rating: 4,
    reviews: 15,
    isNew: true,
    description:
      'Premium quality Khapali wheat flour, stone ground and rich in nutrients.',
  },
  {
    id: 'aata_2',
    name: 'Sharbati Gehun',
    price: '75₹',
    image: images.aata,
    rating: 4,
    reviews: 12,
    isNew: false,
    description:
      'Fine-textured Sharbati wheat flour, perfect for making soft rotis and chapatis.',
  },
  {
    id: 'aata_3',
    name: 'Bajri Aata',
    price: '70₹',
    image: images.aata,
    rating: 5,
    reviews: 18,
    isNew: true,
    description:
      'Nutritious pearl millet flour, high in fiber and essential minerals.',
  },
  {
    id: 'aata_4',
    name: 'Raagi',
    price: '70₹',
    image: images.aata,
    rating: 5,
    reviews: 18,
    isNew: true,
    description:
      'Finger millet flour rich in calcium, perfect for diabetic-friendly meals.',
  },
  {
    id: 'aata_5',
    name: 'Barley',
    price: '70₹',
    image: images.aata,
    rating: 5,
    reviews: 18,
    isNew: true,
    description:
      'Whole grain barley flour, excellent source of dietary fiber and beta-glucans.',
  },
  {
    id: 'aata_6',
    name: 'Sorghum',
    price: '70₹',
    image: images.aata,
    rating: 5,
    reviews: 18,
    isNew: true,
    description:
      'Gluten-free sorghum flour, great for traditional rotis and modern baking.',
  },
  {
    id: 'aata_7',
    name: 'Chaana Aata',
    price: '70₹',
    image: images.aata,
    rating: 5,
    reviews: 18,
    isNew: true,
    description:
      'Chickpea flour packed with protein, ideal for pakoras and gram flour dishes.',
  },
  {
    id: 'aata_8',
    name: 'Gluten Free Aata',
    price: '70₹',
    image: images.aata,
    rating: 5,
    reviews: 18,
    isNew: true,
    description:
      'Special blend of gluten-free flours, perfect for those with celiac disease or gluten sensitivity.',
  },
];

export const daalProducts: ProductItem[] = [
  {
    id: 'daal_1',
    name: 'Arhar Dal',
    price: '120₹',
    image: images.aata,
    rating: 4,
    reviews: 20,
    isNew: false,
    description:
      'Premium split pigeon peas, a staple of Indian cuisine known for rich flavor.',
  },
  {
    id: 'daal_2',
    name: 'Moong Dal',
    price: '140₹',
    image: images.aata,
    rating: 5,
    reviews: 25,
    isNew: true,
    description:
      'Split mung beans, easily digestible and perfect for soups and khichdi.',
  },
  {
    id: 'daal_3',
    name: 'Chana Dal',
    price: '90₹',
    image: images.aata,
    rating: 4,
    reviews: 16,
    isNew: false,
    description:
      'Split Bengal gram, high in protein and ideal for traditional dal preparations.',
  },
  {
    id: 'daal_4',
    name: 'Laal Chana Dal',
    price: '90₹',
    image: images.aata,
    rating: 4,
    reviews: 16,
    isNew: false,
    description:
      'Red chickpeas split, rich in iron and perfect for curries and snacks.',
  },
  {
    id: 'daal_5',
    name: 'Mogar',
    price: '90₹',
    image: images.aata,
    rating: 4,
    reviews: 16,
    isNew: false,
    description:
      'Yellow split mung beans without skin, quick-cooking and light on digestion.',
  },
  {
    id: 'daal_6',
    name: 'Kabuli Chana',
    price: '90₹',
    image: images.aata,
    rating: 4,
    reviews: 16,
    isNew: false,
    description:
      'Large white chickpeas, essential for North Indian curries and chole.',
  },
  {
    id: 'daal_7',
    name: 'Ghughuni Matar',
    price: '90₹',
    image: images.aata,
    rating: 4,
    reviews: 16,
    isNew: false,
    description:
      'Yellow peas, perfect for making traditional Bengali ghugni and street food.',
  },
  {
    id: 'daal_8',
    name: 'Lobia',
    price: '90₹',
    image: images.aata,
    rating: 4,
    reviews: 16,
    isNew: false,
    description:
      'Black-eyed peas, versatile legume great for curries and salads.',
  },
  {
    id: 'daal_9',
    name: 'Rajma',
    price: '90₹',
    image: images.aata,
    rating: 4,
    reviews: 16,
    isNew: false,
    description:
      'Red kidney beans, classic ingredient for rajma chawal and Mexican dishes.',
  },
];

export const gheeAndOilProducts: ProductItem[] = [
  {
    id: 'ghee_1',
    name: 'A2 Bilona Ghee',
    price: '999₹',
    image: images.aata,
    rating: 5,
    reviews: 30,
    isNew: true,
    description:
      'Premium clarified butter made from A2 cow milk using traditional churning method.',
  },
  {
    id: 'ghee_2',
    name: 'Organic Ghee',
    price: '899₹',
    image: images.aata,
    rating: 4,
    reviews: 22,
    isNew: true,
    description:
      'Pure organic ghee made from certified organic cow milk, rich in vitamins A, D, E, and K.',
  },
  {
    id: 'oil_1',
    name: 'Mustard Oil',
    price: '180₹',
    image: images.aata,
    rating: 4,
    reviews: 18,
    isNew: false,
    description:
      'Cold-pressed mustard oil with authentic pungent flavor, ideal for North Indian cooking.',
  },
  {
    id: 'oil_2',
    name: 'Sunflower Oil',
    price: '180₹',
    image: images.aata,
    rating: 4,
    reviews: 18,
    isNew: false,
    description:
      'Light and healthy refined sunflower oil, suitable for all cooking purposes.',
  },
  {
    id: 'oil_3',
    name: 'Groundnut Oil',
    price: '180₹',
    image: images.aata,
    rating: 4,
    reviews: 18,
    isNew: false,
    description:
      'Pure peanut oil with high smoking point, perfect for deep frying.',
  },
  {
    id: 'oil_4',
    name: 'Sesame Oil',
    price: '180₹',
    image: images.aata,
    rating: 4,
    reviews: 18,
    isNew: false,
    description:
      'Cold-pressed sesame oil with rich nutty flavor, great for tempering.',
  },
  {
    id: 'oil_5',
    name: 'Coconut Oil',
    price: '180₹',
    image: images.aata,
    rating: 4,
    reviews: 18,
    isNew: false,
    description:
      'Virgin coconut oil, ideal for South Indian cooking and hair care.',
  },
  {
    id: 'oil_6',
    name: 'Olive Oil',
    price: '180₹',
    image: images.aata,
    rating: 4,
    reviews: 18,
    isNew: false,
    description:
      'Extra virgin olive oil, perfect for salads and Mediterranean cooking.',
  },
  {
    id: 'oil_7',
    name: 'Almond Oil',
    price: '180₹',
    image: images.aata,
    rating: 4,
    reviews: 18,
    isNew: false,
    description:
      'Cold-pressed sweet almond oil, excellent for skin care and aromatherapy.',
  },
];

export const spicesProducts: ProductItem[] = [
  {
    id: 'spice_1',
    name: 'Haldi Powder',
    price: '80₹',
    image: images.aata,
    rating: 4,
    reviews: 25,
    isNew: false,
    description:
      'Pure turmeric powder with high curcumin content, known for its medicinal properties.',
  },
  {
    id: 'spice_2',
    name: 'Jeera Powder',
    price: '120₹',
    image: images.aata,
    rating: 5,
    reviews: 20,
    isNew: true,
    description:
      'Finely ground cumin seeds with intense aroma, essential for Indian cooking.',
  },
  {
    id: 'spice_3',
    name: 'Gota Dhania',
    price: '60₹',
    image: images.aata,
    rating: 4,
    reviews: 15,
    isNew: false,
    description:
      'Whole coriander seeds with citrusy notes, perfect for spice blends.',
  },
  {
    id: 'spice_4',
    name: 'Dhania Powder',
    price: '60₹',
    image: images.aata,
    rating: 4,
    reviews: 15,
    isNew: false,
    description: 'Ground coriander powder, adds warm, nutty flavor to dishes.',
  },
  {
    id: 'spice_5',
    name: 'Mirchi Powder',
    price: '60₹',
    image: images.aata,
    rating: 4,
    reviews: 15,
    isNew: false,
    description:
      'Red chili powder with balanced heat, adds color and spice to dishes.',
  },
  {
    id: 'spice_6',
    name: 'Aamchur',
    price: '60₹',
    image: images.aata,
    rating: 4,
    reviews: 15,
    isNew: false,
    description:
      'Dried mango powder, adds tangy flavor to dishes and chutneys.',
  },
  {
    id: 'spice_7',
    name: 'Sauf',
    price: '60₹',
    image: images.aata,
    rating: 4,
    reviews: 15,
    isNew: false,
    description:
      'Fennel seeds with sweet aroma, used as digestive aid and in cooking.',
  },
];

export const essentialProducts: ProductItem[] = [
  {
    id: 'essential_1',
    name: 'Poha',
    price: '50₹',
    image: images.aata,
    rating: 4,
    reviews: 22,
    isNew: false,
    description: 'Flattened rice flakes, perfect for quick breakfast dishes.',
  },
  {
    id: 'essential_2',
    name: 'Brown Sugar',
    price: '60₹',
    image: images.aata,
    rating: 4,
    reviews: 18,
    isNew: true,
    description:
      'Unrefined sugar with natural molasses, healthier alternative to white sugar.',
  },
  {
    id: 'essential_3',
    name: 'Kala Namak',
    price: '40',
    image: images.aata,
    rating: 5,
    reviews: 25,
    isNew: false,
    description:
      'Black salt with sulfurous taste, essential for chaats and pickles.',
  },
  {
    id: 'essential_4',
    name: 'Row Honey',
    price: '40',
    image: images.aata,
    rating: 5,
    reviews: 25,
    isNew: false,
    description: 'Pure raw honey, unprocessed and rich in natural enzymes.',
  },
  {
    id: 'essential_5',
    name: 'Jaggery Powder',
    price: '40',
    image: images.aata,
    rating: 5,
    reviews: 25,
    isNew: false,
    description:
      'Powdered organic jaggery, natural sweetener rich in minerals.',
  },
  {
    id: 'essential_6',
    name: 'Khandsari Sugar',
    price: '40',
    image: images.aata,
    rating: 5,
    reviews: 25,
    isNew: false,
    description:
      'Traditional raw sugar made from sugarcane juice, minimally processed.',
  },
  {
    id: 'essential_7',
    name: 'Bura',
    price: '40',
    image: images.aata,
    rating: 5,
    reviews: 25,
    isNew: false,
    description: 'Powdered sugar, perfect for desserts and confectionery.',
  },
  {
    id: 'essential_8',
    name: 'Sendha Namak',
    price: '40',
    image: images.aata,
    rating: 5,
    reviews: 25,
    isNew: false,
    description: 'Rock salt used during fasting, rich in natural minerals.',
  },
  {
    id: 'essential_9',
    name: 'Aalu Chips',
    price: '40',
    image: images.aata,
    rating: 5,
    reviews: 25,
    isNew: false,
    description: 'Crispy potato chips made with select potatoes and pure oil.',
  },
  {
    id: 'essential_10',
    name: 'Aalu Papad',
    price: '40',
    image: images.aata,
    rating: 5,
    reviews: 25,
    isNew: false,
    description: 'Sun-dried potato papad, crispy when fried or roasted.',
  },
  {
    id: 'essential_11',
    name: 'Sabudana Chips',
    price: '40',
    image: images.aata,
    rating: 5,
    reviews: 25,
    isNew: false,
    description: 'Crunchy tapioca pearl chips, perfect for fasting days.',
  },
  {
    id: 'essential_12',
    name: 'Chaana Sattu',
    price: '40',
    image: images.aata,
    rating: 5,
    reviews: 25,
    isNew: false,
    description:
      'Roasted gram flour powder, traditional protein-rich supplement.',
  },
  {
    id: 'essential_13',
    name: 'Jau Sattu',
    price: '40',
    image: images.aata,
    rating: 5,
    reviews: 25,
    isNew: false,
    description: 'Roasted barley flour, cooling summer drink ingredient.',
  },
  {
    id: 'essential_14',
    name: 'Wheat Daliya',
    price: '40',
    image: images.aata,
    rating: 5,
    reviews: 25,
    isNew: false,
    description:
      'Broken wheat grains, nutritious breakfast porridge ingredient.',
  },
  {
    id: 'essential_15',
    name: 'Jau Daliya',
    price: '40',
    image: images.aata,
    rating: 5,
    reviews: 25,
    isNew: false,
    description: 'Broken barley grains, high in fiber and beta-glucans.',
  },
  {
    id: 'essential_16',
    name: 'Bajari Daliya',
    price: '40',
    image: images.aata,
    rating: 5,
    reviews: 25,
    isNew: false,
    description: 'Broken pearl millet, rich in minerals and fiber.',
  },
  {
    id: 'essential_17',
    name: 'Bikaneri Papad',
    price: '40',
    image: images.aata,
    rating: 5,
    reviews: 25,
    isNew: false,
    description: 'Traditional spiced lentil papad from Bikaner.',
  },
  {
    id: 'essential_18',
    name: 'Bikaneri Methi Papad',
    price: '40',
    image: images.aata,
    rating: 5,
    reviews: 25,
    isNew: false,
    description: 'Fenugreek flavored crispy lentil papad.',
  },
  {
    id: 'essential_19',
    name: 'Bikaneri Bhujiya',
    price: '40',
    image: images.aata,
    rating: 5,
    reviews: 25,
    isNew: false,
    description: 'Famous spiced gram flour noodle snack from Bikaner.',
  },
  {
    id: 'essential_20',
    name: 'Mangodi',
    price: '40',
    image: images.aata,
    rating: 5,
    reviews: 25,
    isNew: false,
    description: 'Sun-dried moong dal dumplings, used in curries.',
  },
  {
    id: 'essential_21',
    name: 'Aachar',
    price: '40',
    image: images.aata,
    rating: 5,
    reviews: 25,
    isNew: false,
    description:
      'Traditional Indian pickles made with seasonal vegetables and spices.',
  },
];
